name: web_portfolio
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


 
  cupertino_icons: ^1.0.6
  flutter_3d_controller: ^1.3.1
  flutter_animate: ^4.5.2
  reactable: ^0.1.7
  background_bubbles: ^1.0.2
  animated_text_kit: ^4.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^3.0.0


flutter:

 
  uses-material-design: true


  assets:
    - assets/images/
    - assets/files/


  fonts:
    - family: JacquesFracois
      fonts:
        - asset: assets/fonts/JacquesFrancois-Regular.ttf
    #     - asset: fonts/Schyler-Italic.ttf
    #       style: italic
    # - family: Trajan Pro
      # fonts:
    #     - asset: fonts/TrajanPro.ttf
    #     - asset: fonts/TrajanPro_Bold.ttf
    #       weight: 700
  

